name: Daily Webling Check

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  check-open-applications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry install --no-root
    
    - name: Run Webling check
      env:
        WEBLING_API_KEY: ${{ secrets.WEBLING_API_KEY }}
        WEBLING_BASE_URL: ${{ secrets.WEBLING_BASE_URL }}
        WEBLING_MEMBER_GROUP: ${{ secrets.WEBLING_MEMBER_GROUP }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: poetry run python main.py 
