name: Daily Webling Check

on:
  schedule:
    - cron: '30 15 * * *'
  workflow_dispatch:

jobs:
  check-open-applications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run curl command
      run: |
        curl -X POST ${{ secrets.TELEGRAM_WEBHOOK_URL }} \
          -H 'Content-Type: application/json' \
          -H 'X-Telegram-Bot-Api-Secret-Token: ${{ secrets.TELEGRAM_WEBHOOK_SECRET }}' \
          -d '{ "message": { "chat": { "id": "${{ vars.TELEGRAM_CHAT_ID }}" }, "text": "/list quiet" } }'
